// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteSmartHome.Core.Data;

#nullable disable

namespace WebsiteSmartHome.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20250512110445_AddImgToSanPham")]
    partial class AddImgToSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("MaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ChiTietD__3214EC079AE6E40C");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DanhGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DanhGia__3214EC07D09015E8");

                    b.HasIndex("MaSanPham");

                    b.HasIndex(new[] { "MaDonHang", "MaSanPham" }, "UC_DanhGia")
                        .IsUnique();

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__DanhMuc__3214EC07BD778A95");

                    b.HasIndex(new[] { "TenDanhMuc" }, "UQ__DanhMuc__650CAE4EF19C64B0")
                        .IsUnique();

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("MaKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__DonHang__3214EC07E20EBC8F");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.Kho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Kho__3214EC07BC75C3E7");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__Kho__0389B7BDDF5347DE")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.HasIndex(new[] { "TenKho" }, "UQ__Kho__33A304E19BB394EA")
                        .IsUnique();

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__KhuyenMa__3214EC07A503CC05");

                    b.HasIndex(new[] { "TenKhuyenMai" }, "UQ__KhuyenMa__A956B87C202B1025")
                        .IsUnique();

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.LichBaoTri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("LoaiBaoTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaChiTietDonHang")
                        .HasColumnType("int");

                    b.Property<Guid?>("MaYeuCauDichVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBaoTri")
                        .HasColumnType("datetime");

                    b.Property<string>("NguonPhatSinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tự động");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LichBaoT__3214EC0735001FAD");

                    b.HasIndex("MaChiTietDonHang");

                    b.HasIndex("MaYeuCauDichVu");

                    b.ToTable("LichBaoTri", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("MaTaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__NguoiDun__3214EC07F82845AD");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "UQ__NguoiDun__AD7C6528FB4359A4")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.NhaCungCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__NhaCungC__3214EC07F4A15727");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__NhaCungC__0389B7BDC26790F5")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__NhaCungC__A9D10534FF896F7A")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "TenNhaCungCap" }, "UQ__NhaCungC__C6818DB2BC5E7CE6")
                        .IsUnique();

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.PhanCongDichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaKyThuatVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaYeuCau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiPhanCong")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Đang chờ xử lý");

                    b.HasKey("Id")
                        .HasName("PK__PhanCong__3214EC075B79B03E");

                    b.HasIndex("MaKyThuatVien");

                    b.HasIndex("MaYeuCau");

                    b.ToTable("PhanCongDichVu", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKho")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNhaCungCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThoiGianBaoHanh")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__SanPham__3214EC075F75C32E");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex(new[] { "TenSanPham" }, "UQ__SanPham__FCA8046956C1DB55")
                        .IsUnique();

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ xác minh");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC070D16E4F0");

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D1053492856D42")
                        .IsUnique();

                    b.HasIndex(new[] { "TenTaiKhoan" }, "UQ__TaiKhoan__B106EAF836A161B9")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__VaiTro__3214EC071F158C0E");

                    b.HasIndex(new[] { "TenVaiTro" }, "UQ__VaiTro__1DA55814B23A047B")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.YeuCauDichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("ChiPhiYeuCau")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("DaPhanCong")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaChiTietDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayHen")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiYeuCau")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ xử lý");

                    b.HasKey("Id")
                        .HasName("PK__YeuCauDi__3214EC07BC346401");

                    b.HasIndex("MaChiTietDonHang");

                    b.ToTable("YeuCauDichVu", (string)null);
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_DonHang");

                    b.HasOne("WebsiteSmartHome.Core.Data.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_SanPham");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DanhGia", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.DonHang", "MaDonHangNavigation")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_DanhGia_DonHang");

                    b.HasOne("WebsiteSmartHome.Core.Data.SanPham", "MaSanPhamNavigation")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_DanhGia_SanPham");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DonHang", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK_DonHang_KhuyenMai");

                    b.HasOne("WebsiteSmartHome.Core.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_NguoiDung");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.LichBaoTri", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.ChiTietDonHang", "MaChiTietDonHangNavigation")
                        .WithMany("LichBaoTris")
                        .HasForeignKey("MaChiTietDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_LichBaoTri_ChiTietDonHang");

                    b.HasOne("WebsiteSmartHome.Core.Data.YeuCauDichVu", "MaYeuCauDichVuNavigation")
                        .WithMany("LichBaoTris")
                        .HasForeignKey("MaYeuCauDichVu")
                        .HasConstraintName("FK_LichBaoTri_YeuCauDichVu");

                    b.Navigation("MaChiTietDonHangNavigation");

                    b.Navigation("MaYeuCauDichVuNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.NguoiDung", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithOne("NguoiDung")
                        .HasForeignKey("WebsiteSmartHome.Core.Data.NguoiDung", "MaTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDung_TaiKhoan");

                    b.HasOne("WebsiteSmartHome.Core.Data.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDung_VaiTro");

                    b.Navigation("MaTaiKhoanNavigation");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.PhanCongDichVu", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.NguoiDung", "MaKyThuatVienNavigation")
                        .WithMany("PhanCongDichVus")
                        .HasForeignKey("MaKyThuatVien")
                        .IsRequired()
                        .HasConstraintName("FK_PCDV_KyThuatVien");

                    b.HasOne("WebsiteSmartHome.Core.Data.YeuCauDichVu", "MaYeuCauNavigation")
                        .WithMany("PhanCongDichVus")
                        .HasForeignKey("MaYeuCau")
                        .IsRequired()
                        .HasConstraintName("FK_PCDV_YeuCauDichVu");

                    b.Navigation("MaKyThuatVienNavigation");

                    b.Navigation("MaYeuCauNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.SanPham", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_DanhMuc");

                    b.HasOne("WebsiteSmartHome.Core.Data.Kho", "MaKhoNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaKho")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_Kho");

                    b.HasOne("WebsiteSmartHome.Core.Data.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNhaCungCap")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_NhaCungCap");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.YeuCauDichVu", b =>
                {
                    b.HasOne("WebsiteSmartHome.Core.Data.ChiTietDonHang", "MaChiTietDonHangNavigation")
                        .WithMany("YeuCauDichVus")
                        .HasForeignKey("MaChiTietDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_YeuCauDichVu_ChiTietDonHang");

                    b.Navigation("MaChiTietDonHangNavigation");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.ChiTietDonHang", b =>
                {
                    b.Navigation("LichBaoTris");

                    b.Navigation("YeuCauDichVus");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.Kho", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.KhuyenMai", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("PhanCongDichVus");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.TaiKhoan", b =>
                {
                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("WebsiteSmartHome.Core.Data.YeuCauDichVu", b =>
                {
                    b.Navigation("LichBaoTris");

                    b.Navigation("PhanCongDichVus");
                });
#pragma warning restore 612, 618
        }
    }
}
